version: '3'

services:

  fearless-mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=FearlessDemo
      - MYSQL_USER=myapp-user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306

  fearless-main:
    image: fearless-api
    restart: on-failure
    depends_on:
      - fearless-mysql
    ports:
      - 3000:3000
    environment:
      - DATABASE_HOST=fearless-mysql
      - DATABASE_USER=myapp-user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=FearlessInventory
